blog/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include

from rest_framework.routers import DefaultRouter




from blog.settings import develop
from blog.view import TemView
from mainblog.admin import cust_site
# from mainblog.views import post_list,post_detail,links
from mainblog.views import IndexView,CategoryView,TagView,PostDetailView,SearchView,AuthorView
from comment.views import CommentView
from config.views import LinksView
from mainblog.rss import LatestPostFeed
from mainblog.sitemap import PostSitemap
from django.contrib.sitemaps import views as sitemap_views
from blog.autocomplete import CategoryAutocomplete,TagAutocomplete




# urlpatterns = [
#
#     re_path(r'^$',post_list,name='index'),
#     re_path(r'^category/(?P<category_id>\d+)/$',post_list,name='category-list'),
#     re_path(r'^tag/(?P<tag_id>\d+)/$',post_list,name='tag-list'),
#     re_path(r'^post/(?P<post_id>\d+).html$',post_detail,name='post-detail'),
#     re_path(r'^links/$',links,name='links'),
#     re_path(r'^superadmin/', admin.site.urls,name='super-admin'),
#     re_path(r'^admin/',cust_site.urls,name='admin'),
# ]
#
# from mainblog.apis import PostViewSet
# router = DefaultRouter()
# router.register(r'post',PostViewSet,)

urlpatterns = [

    re_path(r'^$',IndexView.as_view(),name='index'),
    re_path(r'^search/$',SearchView.as_view(),name='search'),
    re_path(r'^author/(?P<owner_id>\d+)/$',AuthorView.as_view(),name='author'),
    re_path(r'^category/(?P<category_id>\d+)/$',CategoryView.as_view(),name='category-list'),
    re_path(r'^tag/(?P<tag_id>\d+)/$',TagView.as_view(),name='tag-list'),
    re_path(r'^post/(?P<post_id>\d+).html$',PostDetailView.as_view(),name='post-detail'),
    re_path(r'^links/$',LinksView.as_view(),name='links'),
    re_path(r'^comment/$',CommentView.as_view(),name='comment'),
    re_path(r'^superadmin/', admin.site.urls,name='super-admin'),
    re_path(r'^admin/',cust_site.urls,name='admin'),
    re_path(r'^rss|feed/',LatestPostFeed(),name='rss'),
    re_path(r'^sitemap\.xml$',sitemap_views.sitemap,{'sitemaps':{'post':PostSitemap}}),
    re_path(r'^category-autocomplete/$',CategoryAutocomplete.as_view(),name='category-autocomplete'),
    re_path(r'^tag-acutocomplete/$',TagAutocomplete.as_view(),name='tag-autocomplete'),
    re_path(r'^ckeditor/',include('ckeditor_uploader.urls')),
    # re_path(r'^api/post/',post_list,name='post_list'),
    # # re_path(r'^api/post/',PostList.as_view(),name='post_list')
    # re_path(r'^api/',include(router.urls))
    re_path(r'^user/',include(('user.urls','user'),namespace='user')),
    re_path(r'^image/',include(('image.urls','image'),namespace='image')),
    re_path(r'tem/',TemView,name='tem'),

]+static('/media/',document_root='/home/wanpeng/Desktop/django_blackhorse/django_blog/blog/media')


if develop.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/',include(debug_toolbar.urls)),
    ] + urlpatterns

blog/user/urls.py
from django.conf.urls.static import static
from django.urls import re_path
from user.views import UserLogin,UserRegister,UserLogout,UserDetail,UserDetailChange
from blog.settings import develop

urlpatterns = [

    re_path(r'login',UserLogin.as_view(),name='login'),
    re_path(r'logout',UserLogout,name='logout'),
    re_path(r'register',UserRegister.as_view(),name='register'),
    re_path(r'^userinfo/(?P<user_id>\d+)/(?P<sort>\w+)',UserDetail.as_view(),name='userdetail'),
    re_path(r'^userinfochange',UserDetailChange.as_view(),name='userdetailchange'),
    ]

blog/user/models.py
from django.db import models

# Create your models here.

#改写django 自带的 User 类
from django.contrib.auth.models import AbstractUser
#设置settings.AUTH_USER_MODEL = '应用名.类名'
# username,password,email,first_name,last_name,is_superuser,is_staff,is_active,last_login,date_joined
#user = authenticate(username=username,password=password)
#set_password('password')
#login(request,user) 保持登录状态，存session
# login_required,装饰器验证登录，未登录跳转指定地址 settings.LOGIN_URL
# logout(request) 登录状态取消

class UserInfo(AbstractUser):

    default_sign = "这里什么都没有"


    # 在django 自带的User类里面增加手机号，昵称，头像，签名，简介和更新时间
    phone = models.CharField(max_length=11,default='')
    nickname = models.CharField(max_length=11,verbose_name='昵称')
    avatar = models.ImageField(upload_to='avatar',null=True,default='avatar/default/1.jpeg')
    sign = models.CharField(max_length=50,verbose_name='签名',default=default_sign)
    info = models.CharField(max_length=150,verbose_name='个人简介',default='')
    updated_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name=verbose_name_plural='用户信息'
        #db_table = '数据库名字'

    def __str__(self):
        return self.username

blog/user/forms.py
import re

from ckeditor_uploader.widgets import CKEditorUploadingWidget
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, HTML, Field
from django import forms
from .models import UserInfo

class RegisterForms(forms.ModelForm):

    username = forms.CharField(
        label='姓名',
        min_length=4,
        max_length=50,
        widget=forms.TextInput,
    )

    email = forms.CharField(
        label='电子邮箱',
        min_length=4,
        max_length=50,
        widget=forms.EmailInput,
    )

    phone = forms.CharField(
        label='手机号码',
        min_length=11,
        max_length=50,
        widget=forms.NumberInput,
    )

    password = forms.CharField(
        label='密码',
        min_length=8,
        max_length=16,
        widget=forms.PasswordInput,
    )

    password_confirm = forms.CharField(
        label='确认密码',
        min_length=8,
        max_length=16,
        widget=forms.PasswordInput,
    )

    class Meta:
        model=UserInfo
        fields = ['username','email','phone','password','password_confirm']

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for name,field in self.fields.items():
            # field.widget.attrs.update({'class':'form-control ','placeholder':'请输入%s'%field.label,'style':'width:30%;'})
            field.widget.attrs.update(
                {'class': 'form-control '})

    def clean_username(self):
        post_username = self.cleaned_data['username']

        if UserInfo.objects.filter(username=post_username):
            raise forms.ValidationError('名称已注册')
        return post_username

    def clean_email(self):
        post_email = self.cleaned_data['email']
        if UserInfo.objects.filter(email=post_email):
            raise forms.ValidationError('邮箱已注册')
        return post_email

    def clean_phone(self):
        post_phone = self.cleaned_data['phone']
        if UserInfo.objects.filter(phone=post_phone):
            raise forms.ValidationError('手机号已注册')
        return post_phone

    #密码强度验证正则表达式
    psw_re = r'^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,16}$'


    def clean_password(self):
        post_password = self.cleaned_data['password']
        if not re.match(self.psw_re,post_password):
            raise forms.ValidationError('密码不符合规范，8-16位，密码需包含数字，大写和小写字母！')
        return post_password



    def clean_password_confirm(self):
        post_password_confirm = self.cleaned_data['password_confirm']
        #这一步是为了让上下password 和 password confirm 都能报错 密码格式不对
        try:
            post_password = self.cleaned_data['password']
        except Exception as e:
            raise forms.ValidationError('密码不符合规范，8-16位，密码需包含数字，大写和小写字母！')
        else:
            if post_password != post_password_confirm:
                raise forms.ValidationError('密码不一致')
        return post_password_confirm

        # self.helper = FormHelper()
        # Fields = []
        #
        # for name,field in self.fields.items():
        #     Fields.append(Field(name,css_class='form-control item',placeholder='请输入%s'%field.label))
        #
        # self.helper.layout = Layout(
        #     Div(
        #         HTML('<span><i class="icon icon-user"></i></span>'),
        #         css_class='form-icon'
        #     ),
        #     #
        #     *Fields,
        #     Field('username', css_class='form-control item', placeholder='请输入')
        # )

class LoginForms(forms.ModelForm):

    account = forms.CharField(
        label='账号',
        min_length=4,
        max_length=50,
        widget=forms.TextInput(attrs={'placeholder':"用户名 or Email or 手机号"}),
        # error_messages='该用户不存在'
    )

    password = forms.CharField(
        label='密码',
        min_length=4,
        max_length=50,
        widget=forms.PasswordInput(attrs={'placeholder':'请输入密码'}),
    )


    class Meta:
        model=UserInfo
        fields = ['account','password',]



    # numregex = r'^1\d{10}$'
    # emaregex = r'\w+@\w+.com'
    #
    # def clean_account(self):
    #     account=self.cleaned_data['account']
    #     if account.isdigit() and re.match(self.numregex,account):
    #         phone = re.match(self.numregex,account).group()
    #         userobj=UserInfo.objects.filter(phone=phone)
    #     elif re.match(self.emaregex,account):
    #         email = re.match(self.emaregex,account).group()
    #         userobj = UserInfo.objects.filter(email=email)
    #     else:
    #         userobj = UserInfo.objects.filter(username=account)
    #
    #     if not userobj:
    #         raise forms.ValidationError('未找到该用户，请重试')
    #
    #     return userobj
    #
    #
    # def clean_password(self,):
    #     password=self.cleaned_data['password']
    #     userobj = self.cleaned_data['account']
    #
    #     password

class UserInfoForms(forms.ModelForm):

    avatar = forms.ImageField(required=False,)
    phone = forms.CharField(required=False,)

    info = forms.CharField(widget=CKEditorUploadingWidget(), label='个人简介', required=False)
    nickname = forms.CharField(required=False,label='昵称')

    class Meta:
        model = UserInfo
        fields = ['avatar','username','nickname','phone','email','sign','info',]

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for name,f in self.fields.items():
            f.widget.attrs.update({'class':'form-control'})





blog/user/views.py
import re

from django.contrib.auth import authenticate, logout, login
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.views import View

from mainblog.models import Post
from .forms import RegisterForms
from django.views import generic
from user.models import UserInfo
from user.forms import RegisterForms,LoginForms,UserInfoForms
from user.tools.password_tools import pw_md5



#Create your views here.
'''登录'''
class UserLogin(View):
    template_name = 'user/login.html'

    '''验证account的正则表达式（用户名，手机号码, Email）'''
    numregex = r'^1\d{10}$'
    emaregex = r'\w+@\w+.com'

    def get(self,request):
       #response = super().get(request,*args, **kwargs)
       userforms = LoginForms()
       context = {
           #"request":request,
           "form":userforms,
       }
       return render(request,self.template_name,context)

    def post(self,request):
        userforms=LoginForms(request.POST)
        '''先验证基本数据长度'''
        if userforms.is_valid():
            '''验证密码分两步：'''
            '''1.验证账号是否存在：'''
            '''区分不同账号类型（username，Email，Phone）'''
            account=userforms.cleaned_data['account']
            if account.isdigit() and re.match(self.numregex,account):
                # phone = re.match(self.numregex,account).group()
                userobj=UserInfo.objects.filter(phone=account)
            elif re.match(self.emaregex,account):
                # email = re.match(self.emaregex,account).group()
                userobj = UserInfo.objects.filter(email=account)
            else:
                userobj = UserInfo.objects.filter(username=account)
            '''不存在就生成错误提示'''
            '''存在账号则进入到密码验证（在register部分会规定每个账号数值只有一个，所以这里只有有一个或没有两种情况,不存在两个账号）'''
            if not userobj:
                message = "账号不存在,请重试!"
                #pass

            else:
                for user in userobj:
                    post_password = userforms.cleaned_data['password']
                    #user_password = userobj.password
                    #p_p_m = pw_md5(post_password)
                    #if user_password == p_p_m:
                    #session中存入用户id,姓名，和登录状态
                    '''django 有一套验证密码的接口（密码存入django后台admin会加密）'''
                    if authenticate(username=user.username,password=post_password):
                        # request.session['user_id'] = user.id
                        request.session['user_name'] = user.username
                        request.session['is_login'] = True
                        # 同时登录后台admin
                        login(request, UserInfo.objects.filter(username=request.session['user_name']).first())
                        return HttpResponseRedirect(reverse('index'))

                    else:
                        message = "用户名或密码错误，请重试!"
                        #pass

            context = {
                'form':userforms,
                'message':message,
            }
            return render(request,self.template_name,context)

'''注册'''
class UserRegister(View):

    template_name = 'user/register.html'

    def get(self,request):
        userforms=RegisterForms()
        context = {
            "form":userforms,
        }
        return render(request,self.template_name,context)


    def post(self,request):
        userforms = RegisterForms(request.POST)

        '''初步数据验证OK(包括密码强度；密码一致性；用户名，邮箱，手机号唯一性；正确格式等)'''
        if userforms.is_valid():
            '''存储加密后的密码'''
            password = userforms.cleaned_data['password']
            instance = userforms.save(commit=False)
            #instance.password = pw_md5(password)
            '''django 自身有一套加密算法加密密码 object.set_password'''
            instance.set_password(password)
            '''session中存入,姓名，和登录状态'''
            '''没有id，因为id是存进去后mysql自增的'''
            request.session['user_name'] = instance.username
            request.session['is_login'] = True


            print(instance.username)

            instance.save()
            userforms.save_m2m()
            # 同时登录后台admin
            login(request, UserInfo.objects.filter(username=request.session['user_name']).first())

            return HttpResponseRedirect(reverse('index'))
        else:
            message = '注册失败，请重试'
        context = {
            'form':userforms,
            'message':message,
        }
        return render(request,self.template_name,context)

'''登出'''
def UserLogout(request):

    '''登出blog'''
    request.session.flush()
    '''登出admin后台'''
    logout(request)

    return HttpResponseRedirect(reverse('index'))

'''用户信息'''
class UserDetail(View):

    def get(self,request,user_id,sort):

        login_id = request.user_id
        #print(type(login_id))
        #print(user_id)
        #print(str(login_id)==user_id)
        user_detail = UserInfo.objects.filter(id=user_id)

        user_blogs = None

        if sort == 'lasted':
            user_blogs = Post.latest_posts().filter(id=user_id)
        elif sort == 'hot':
            user_blogs = Post.hot_posts().filter(id=user_id)

        '''如果登录用户和要访问的用户一致，给出全部信息'''
        if str(login_id) == user_id:
            context = {
                'user_detail':user_detail,
                'is_self':True,
                'user_blogs':user_blogs,
            }
            return render(request,'user/userdetail.html',context)
        else:
            """如果登录用户和要访问的用户不一致，给出部分信息"""
            user_detail= user_detail.values('username','nickname','email','avatar','sign','info','last_login')
            context = {
                'user_detail': user_detail,
                'is_self': False,
                'user_blogs': user_blogs,
            }
            return render(request, 'user/userdetail.html', context)


class UserDetailChange(View):


    # 直接采用django admin 后台 user 编辑页面
    def get(self,request):

        user_object = UserInfo.objects.filter(id=request.user_id).first()
        user_forms =UserInfoForms(instance=user_object)
        context={
            'form':user_forms,
        }

        return render(request, 'user/userdetailchange.html', context)

    def post(self,request):

        user_object = UserInfo.objects.filter(id=request.user_id).first()
        user_forms = UserInfoForms(request.POST,request.FILES,instance=user_object)

        if user_forms.is_valid():
            user_forms.save()
            return HttpResponseRedirect(reverse('user:userdetail',args=[request.user_id,'lasted']))
        else:
            context = {
                'form': user_forms,
            }
            return render(request,'user/userdetailchange.html', context)

blog/themes/bootstrap/templates/user/login.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block pagefirst %}
{% endblock %}

{% block other %}
<div class="container-fluid " style="max-height:90%;border:1px solid rgb(180,180,180);border-radius:10px;color: rgb(255,255,255);width:30%;margin-top: 5%;padding:30px 50px 50px 50px;background-color:rgba(32,32,32,0.8); ">
    {% block form %}
    <div class='text-center' style="padding-bottom: 10px">
        <h1>登录</h1>
    </div>
    <form class="login" method="POST" action="{% url 'user:login' %}" novalidate>
        {% csrf_token %}

        <div class="m-auto" style="width: 80%">
            {{ form|crispy }}
            <span style="font-size: 15px;font-weight: bold;color: rgb(255,0,0);">{{ message }}</span>

        </div>

        <div  style="text-align: right;width: 90%" >
            <a href={% url 'tem' %}>忘记密码了？</a>
            <a href={% url 'tem' %}>忘记帐号了？</a>
            <button class="btn btn-info btn-sm rounded-0 " type="submit">登录</button>
             <a href={% url 'user:register' %} style="margin:5px">注册</a>
        </div>
    </form>
    {% endblock %}
</div>
{% endblock %}

{% block main %}
{% endblock %}

blog/themes/bootstrap/templates/user/register.html
{% extends 'user/login.html' %}
{% load crispy_forms_tags %}

{% block form %}
    <div class='text-center' style="padding-bottom: 10px">
        <h1>注册</h1>
    </div>
    <form class="login" method="POST" action="{% url 'user:register' %}" novalidate>
        {% csrf_token %}

        <div class="m-auto" style="width: 80%">
            {{ form|crispy }}
            <span style="font-size: 15px;font-weight: bold;color: rgb(255,0,0);">{{ message }}</span>
        </div>

        <div  style="text-align: right;width: 90%" >
             <a href={% url 'user:login' %} style="margin-right:45%;">已有帐号登录</a>
            <button class="btn btn-info btn-sm rounded-0 " type="submit">注册</button>
        </div>
    </form>
{% endblock %}

blog/themes/bootstrap/templates/user/userdetail.html


{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block pagefirst %}
{% endblock %}

{%  block right %}
{#    用户详情页面#}

    <div class="card rounded-0 px-3 px-lg-4" style="margin-top: 5%">
        <div class="card-header text-center bg-white py-2"><h3 class="my-1 text-info">个人资料</h3></div>
        <div class="card-body">
            <ul class="list-group">
             {%  for user in user_detail %}
                <li class="list-group-item text-center border-0" id="profile-avatar">
                    <img src="{{ user.avatar.url }}"/>
                </li>

                <li class="list-group-item  border-0">
                    <span class="font-weight-bold">用户名：</span>
                    <span>{{ user.username }}</span>
                </li>

                <li class="list-group-item  border-0">
                     <span class="font-weight-bold">昵&emsp;称：</span>
                    <span>{{ user.nickname }}</span>
                </li>

                <li class="list-group-item  border-0" >
                    <span class="font-weight-bold">邮 &emsp;箱：</span>
                    <span>{{ user.email }}</span>
                </li>
{#                 是本人就显示敏感信息#}
                {%  if is_self %}
                    <li class="list-group-item  border-0">
                        <span class="font-weight-bold">手&emsp;机：</span>
                        <span>{{ user.phone }}</span>
                    </li>
                {% endif %}

                 <li class="list-group-item  border-0">
                    <span class="font-weight-bold">最后登录：</span>
                    <span>{{ user.last_login }}</span>
                </li>

            {% endfor %}
            </ul>
        </div>
        {%  if is_self %}
            <div class="text-center mb-5" id="social-login">
                <div class="more-link mt-3">
                    <a class="btn btn-info btn-sm rounded-0 mx-lg-3 mx-sm-2" href="/admin/user/userinfo/{{ request.user_id }}/change">修改资料</a>
                    <a class="btn btn-info btn-sm rounded-0 mx-lg-3 mx-sm-2" href="/admin/mainblog/post/">修改文章</a>
                    <a class="btn btn-info btn-sm rounded-0 mx-lg-3 mx-sm-2" href="#">修改密码</a>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block left %}

    <div class="card rounded-0 px-3 px-lg-4" style="margin-top: 2.5%">
            <div class="text-secondary font-weight-bold py-2 f-15 choice">
                {% url 'user:userinfo' user.id as base_index %}
                {% url 'user:userinf_hot' user.id as hot_index %}
             {%  for user in user_detail %}
                <a class="pb-2 ml-4 {% if sort == 'lasted' %}active{% endif %}" href="{% url 'user:userdetail' user.id 'lasted' %}">
                    <i class="fa fa-fire mr-1"></i>时间排序</a>
                <a class="pb-2 ml-4 {% if sort == 'hot' %}active{% endif %}" href="{% url 'user:userdetail' user.id 'hot' %}">
                    <i class="fa fa-fire mr-1"></i>热度排序</a>
            {% endfor %}
            </div>

            {% for blog in user_blogs %}
        <div class="card post">
            <div class="card-body">
                <h5 class="card-title"><a href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h5>
                <span class="card-link">作者:<a href="{% url 'author' post.owner_id %}">{{ post.owner.username }}</a></span>
                <span class="card-link">分类:<a href="{% url 'category-list' post.category_id %}">{{ post.category.name }}</a></span>
                 <span class="card-link">标签:
                    {% for tag in post.tag.all %}
                    <a href="{% url 'tag-list' tag.id %}">{{ tag.name }}</a>
                    {% endfor %}
                </span>
                <hr/>
                <p class="card-text">{{ post.desc }}<a href="{% url 'post-detail' post.id %}">完整内容</a></p>
            </div>
        </div>
        {% endfor%}
    </div>
{% endblock %}


blog/themes/bootstrap/templates/user/userdetailchange.html

{#这个页面备用，实际是直接采用admin User 的 编辑页面#}

{% extends 'user/login.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block pagefirst %}
{% endblock %}

{% block other %}
<div class="container-fluid" style="max-height:90%;border:1px solid rgb(180,180,180);border-radius:10px;color: rgb(255,255,255);width:90%;margin-top: 5%;padding:30px 50px 50px 50px;background-color:rgba(32,32,32,0.8); ">
    <div class='text-center' style="padding-bottom: 10px">
        <h1>修改用户资料</h1>
    </div>
    <form class="login" method="POST" action="{% url 'user:userdetailchange' %}" enctype="multipart/form-data" novalidate>
        {% csrf_token %}

        <div class="m-auto" style="width:80%">
            {{ form|crispy }}
            <span style="font-size: 15px;font-weight: bold;color: rgb(255,0,0);">{{ message }}</span>
        </div>


        <div  style="text-align: right;width: 90%" >
             <a href='#' style="margin-right:45%;">修改密码</a>
            <button class="btn btn-info btn-sm rounded-0 " type="submit">提交资料</button>
        </div>
    </form>

{% endblock %}
