blog/blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include

from rest_framework.routers import DefaultRouter




from blog.settings import develop
from blog.view import TemView
from mainblog.admin import cust_site
# from mainblog.views import post_list,post_detail,links
from mainblog.views import IndexView,CategoryView,TagView,PostDetailView,SearchView,AuthorView
from comment.views import CommentView
from config.views import LinksView
from mainblog.rss import LatestPostFeed
from mainblog.sitemap import PostSitemap
from django.contrib.sitemaps import views as sitemap_views
from blog.autocomplete import CategoryAutocomplete,TagAutocomplete




# urlpatterns = [
#
#     re_path(r'^$',post_list,name='index'),
#     re_path(r'^category/(?P<category_id>\d+)/$',post_list,name='category-list'),
#     re_path(r'^tag/(?P<tag_id>\d+)/$',post_list,name='tag-list'),
#     re_path(r'^post/(?P<post_id>\d+).html$',post_detail,name='post-detail'),
#     re_path(r'^links/$',links,name='links'),
#     re_path(r'^superadmin/', admin.site.urls,name='super-admin'),
#     re_path(r'^admin/',cust_site.urls,name='admin'),
# ]
#
# from mainblog.apis import PostViewSet
# router = DefaultRouter()
# router.register(r'post',PostViewSet,)

urlpatterns = [

    re_path(r'^$',IndexView.as_view(),name='index'),
    re_path(r'^search/$',SearchView.as_view(),name='search'),
    re_path(r'^author/(?P<owner_id>\d+)/$',AuthorView.as_view(),name='author'),
    re_path(r'^category/(?P<category_id>\d+)/$',CategoryView.as_view(),name='category-list'),
    re_path(r'^tag/(?P<tag_id>\d+)/$',TagView.as_view(),name='tag-list'),
    re_path(r'^post/(?P<post_id>\d+).html$',PostDetailView.as_view(),name='post-detail'),
    re_path(r'^links/$',LinksView.as_view(),name='links'),
    re_path(r'^comment/$',CommentView.as_view(),name='comment'),
    re_path(r'^superadmin/', admin.site.urls,name='super-admin'),
    re_path(r'^admin/',cust_site.urls,name='admin'),
    re_path(r'^rss|feed/',LatestPostFeed(),name='rss'),
    re_path(r'^sitemap\.xml$',sitemap_views.sitemap,{'sitemaps':{'post':PostSitemap}}),
    re_path(r'^category-autocomplete/$',CategoryAutocomplete.as_view(),name='category-autocomplete'),
    re_path(r'^tag-acutocomplete/$',TagAutocomplete.as_view(),name='tag-autocomplete'),
    re_path(r'^ckeditor/',include('ckeditor_uploader.urls')),
    # re_path(r'^api/post/',post_list,name='post_list'),
    # # re_path(r'^api/post/',PostList.as_view(),name='post_list')
    # re_path(r'^api/',include(router.urls))
    re_path(r'^user/',include(('user.urls','user'),namespace='user')),
    re_path(r'^image/',include(('image.urls','image'),namespace='image')),
    re_path(r'tem/',TemView,name='tem'),

]+static('/media/',document_root='/home/wanpeng/Desktop/django_blackhorse/django_blog/blog/media')


if develop.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/',include(debug_toolbar.urls)),
    ] + urlpatterns

blog/user/urls.py
from django.conf.urls.static import static
from django.urls import re_path
from user.views import UserLogin,UserRegister,UserLogout,UserDetail,UserDetailChange
from blog.settings import develop

urlpatterns = [

    re_path(r'login',UserLogin.as_view(),name='login'),
    re_path(r'logout',UserLogout,name='logout'),
    re_path(r'register',UserRegister.as_view(),name='register'),
    re_path(r'^userinfo/(?P<user_id>\d+)/(?P<sort>\w+)',UserDetail.as_view(),name='userdetail'),
    re_path(r'^userinfochange',UserDetailChange.as_view(),name='userdetailchange'),
    ]

blog/themes/bootstrap/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}首页{% endblock %}—Blog wanpeng‘s博客系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!--<link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.css" media="screen">-->
    <script src={% static 'js/jquery.js' %}></script>
    <script src={% static 'js/bootstrap.js' %}></script>

    {% block extra_head %}
    {% endblock %}

    <style>
    .post {
        margin-bottom: 5px;
    }
    html,
    body{
        height: 100%;
        width: 100%;
        margin:0;
        padding:0;
    }
    #container{
        min-width: 100%;
        min-height: 100%;
        height:auto !important;
        margin:0 auto -60px;
        {#position: relative;#}
    }
    .push
    footer{
        height:60px;
        {#bottom:0;#}
        {#position: absolute;#}
        width: 100%;
    }
    </style>
  </head>

  <body>
      <div class="container-fluid" id="container" style="background-image: url('{% static "img/b.jpg" %}');background-repeat: no-repeat;background-size: 100% 100%">
        <div class="container-fluid head">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
              <a class="navbar-brand" href="/">首页</a>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">

              <!--分类-->
                <ul class="navbar-nav mr-auto">
                {% for cate in nav_category %}    <!---->
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'category-list' cate.id %}">{{ cate.name }}</a>
                  </li>
                {% endfor %}
                </ul>

              <!--搜索-->
                <form class="form-inline" action='/search/' method='GET'>
                    <input class="form-control" type="search" name="keyword" placeholder="Search" aria-label="Search" value="{{ keyword }}">
                  <button class="btn btn-outline-success" type="submit">搜索</button>
                </form>

              <!--注册-->
                <ul class="navbar-nav">
                    {% if request.is_login %}
    {#                {% get_notifications_count user 'false' as msgnum %}#}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false" title="{{ request.user_name }}，欢迎回来！">
    {#                        {% if msgnum > 0%}#}
    {#                        <span class="get-msg text-center">{{ msgnum }}</span>#}
    {#                        {% endif %}#}
    {#                        {% get_user_avatar_tag user %}#}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right mt-0 rounded-0 border-0" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item pl-3" href={% url 'user:userdetail' request.user_id 'lasted' %}><i class="fa fa-fw fa-user text-info mr-2"></i>个人资料</a>
                            {% if request.is_staff %}
                            <a class="dropdown-item pl-3" href="/admin"><i
                                    class="fa fa-fw fa-key text-info mr-2"></i>后台管理</a>
                            {% endif %}
    {#                        <a class="dropdown-item pl-3" href="{% url 'comment:notification' %}"><i class="fa fa-fw fa-bell text-info mr-2"></i>消息#}
    {#                            {% if msgnum > 0%}#}
    {#                            <span class="badge badge-warning ml-3 text-center">{{ msgnum }}</span>#}
    {#                            {% endif %}#}
    {#                        </a>#}
                            <a class="dropdown-item pl-3" href={% url 'user:logout' %}><i
                                    class="fa fa-fw fa-sign-out text-info mr-2"></i>退出</a>
                        </div>
                    </li>
                    {% else %}
                    <li class="nav-item mr-2">
                        <a class="nav-link py-md-3" href="{% url 'user:login' %}?next={{ request.path }}">登录</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link py-md-3" href="{% url 'user:register' %}?next={{ request.path }}">注册</a>
                    </li>
                    {% endif %}
                </ul>

              </div>
            </nav>

        {% block pagefirst %}
            <div class="jumbotron">
                <h1 class="display-4">Blog</h1>
                <p class="lead">基于Django的多人博客系统</p>
            </div>
        {% endblock %}

        </div>


         {% block other %}  <!--登陆界面处-->
         {% endblock %}   <!---->


        {% block main %}
        <div class="container-fluid main">
            <div class="row">
                <div class="col-8 post-list">
                {% block left %}  <!---->
                {% endblock %}   <!---->
                </div>

                <div class="col-4">
                    {% block right %}  <!---->
                    {% endblock %}
                </div>
            </div>
        </div>
        {% endblock %}

        <div class="push"></div>
      </div>


    <footer class="footer">
        {% block footer %}
        <div class="container-fluid">
            <hr/>
            <nav class="nav category">
            {% for cate in normal_category %} <!---->
            <a href="{% url 'category-list' cate.id %}" class="nav-link">{{ cate.name }}</a>
            {% endfor %}
            </nav>
        </div>
        <div class="container-fluid power">
            <span class="text-muted">Power by Blog@wanpeng</span>
        </div>
        {% endblock %}
    </footer>

  </body>
</html>

blog/themes/bootstrap/templates/blog/detail.html
{% extends "./base.html" %}

{% load comment_block %}

{% block title %} {{ post.title }} {% endblock %}

{% block extra_head %}
<link rel="stylesheet" href="http://cdn.bootcss.com/highlight.js/8.0/styles/monokai_sublime.min.css">
<script src="https://cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

{% block left %}
    {% if post %}
    <h1>{{ post.title }}</h1>
    <div>
        <span>分类:<a href="{% url 'category-list' post.category_id %}">{{ post.category.name }}</a></span>
        <span>作者:<a href="{% url 'author' post.owner_id %}">{{ post.owner.username }}</a></span>
        <span>创建时间:{{ post.created_time }}</span>
        <span>pv/uv:{{ post.pv }}/{{ post.uv }}</span>
    </div>
    <hr/>
    <p>

        {{ post.content }}

    </p>
    <p>
        {% autoescape off %}
        {{ post.content_html }}
        {% endautoescape %}
    </p>
    {% endif %}

    {% comment_block request.path %}
    {{ request.path }}

{% endblock %}

{% block right %}  <!---->
    {% for sidebar in sidebars %}
    <div class="card sidebar">
        <div class="card-body">
            <h4 class="card-title">{{ sidebar.title }}</h4>
            <p>
            {{ sidebar.content_html }}
            </p>
        </div>
    </div>
    {% endfor %}
{% endblock %}

blog/themes/bootstrap/templates/blog/list.html
{% extends "./base.html" %}

{% block title %}
    {% if tag %}
    标签页: {{ tag.name }}
    {% elif category %}
    分类页: {{ category.name }}
    {% else %}
    首页
    {% endif %}
{% endblock %}


{% block left %}
    {% for post in post_list %}
    <div class="card post">
        <div class="card-body">
            <h5 class="card-title"><a href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h5>
            <span class="card-link">作者:<a href="{% url 'author' post.owner_id %}">{{ post.owner.username }}</a></span>
            <span class="card-link">分类:<a href="{% url 'category-list' post.category_id %}">{{ post.category.name }}</a></span>
             <span class="card-link">标签:
                {% for tag in post.tag.all %}
                <a href="{% url 'tag-list' tag.id %}">{{ tag.name }}</a>
                {% endfor %}
            </span>
            <hr/>
            <p class="card-text">{{ post.desc }}<a href="{% url 'post-detail' post.id %}">完整内容</a></p>
        </div>
    </div>
    {% endfor %}

    {% if page_obj %}
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
    {% endif %}
        Page {{ page_obj.number }} of {{ paginator.num_pages }}.
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">下一页</a>
    {% endif %}
    {% endif %}

{% endblock %}


{% block right %}  <!---->
    {% for sidebar in sidebars %}
    <div class="card sidebar">
        <div class="card-body">
            <h4 class="card-title">{{ sidebar.title }}</h4>
            <p>
            {{ sidebar.content_html }}
            </p>
        </div>
    </div>
    {% endfor %}
{% endblock %}